#!/usr/bin/env python3
"""Assemble build/<id>.{html,css} into sections.css + index.html. Idempotent."""
import re, pathlib

ROOT = pathlib.Path(__file__).parent
# NB: 'fab' is intentionally NOT here — it's a viewport-fixed sticky button
# hardcoded in index.html OUTSIDE .canvas (fixed positioning needs a
# non-transformed ancestor).
ORDER = ['hero', 'main', 'mission', 'steps', 'icons', 'maps', 'rules',
         'booking', 'footer']

# ---- sections.css ----
css = ["/* AUTO-GENERATED by assemble.py — edit build/<id>.css, then re-run. */"]
for s in ORDER:
    css.append(f"\n/* ===================== {s} ===================== */")
    css.append((ROOT / 'build' / f'{s}.css').read_text().rstrip())
# Assembly fixes: nested children of button/badge containers need explicit
# position:absolute (the base ".sec > *" rule only reaches direct children).
css.append("\n/* assembly fixes — absolutely position nested button/badge children */")
css.append(".sec--hero .hero-cta > *,\n"
           ".sec--hero .hero-badge > *,\n"
           ".sec--booking .booking__btn > * { position: absolute; }")
(ROOT / 'sections.css').write_text('\n'.join(css) + '\n')

# ---- inject HTML between markers ----
html = (ROOT / 'index.html').read_text()
block = '\n\n'.join((ROOT / 'build' / f'{s}.html').read_text().rstrip() for s in ORDER)
block = '\n'.join('      ' + ln if ln.strip() else ln for ln in block.splitlines())
new = re.sub(r'<!-- SECTIONS:START -->.*?<!-- SECTIONS:END -->',
             '<!-- SECTIONS:START -->\n' + block + '\n      <!-- SECTIONS:END -->',
             html, flags=re.S)
(ROOT / 'index.html').write_text(new)
print(f"assembled {len(ORDER)} sections -> sections.css + index.html")
